FIELD_SIZE = 32
FIELD_PARTS = 20
CANVAS_WIDTH = FIELD_SIZE * FIELD_PARTS
CANVAS_HEIGHT = FIELD_SIZE * FIELD_PARTS

SNAKE_DEFAULT_PARTS = 3
SNAKE_DEFAULT_POSITION_X = FIELD_PARTS // 2
SNAKE_DEFAULT_POSITION_Y = FIELD_PARTS // 2

SNAKE_HEAD = 'snake_head'
SNAKE_BODY = 'snake_body'
SNAKE_TAIL = 'snake_tail'
